#[cfg(all(feature = "tpm1_2", not(feature = "tpm2_0")))]
pub use crate::tlcl::tpm12::constants::{
  TPM_NV_PER_AUTHREAD as NV_PERM_AUTHREAD, TPM_NV_PER_AUTHWRITE as NV_PERM_AUTHWRITE,
  TPM_NV_PER_GLOBALLOCK as NV_PERM_GLOBALLOCK, TPM_NV_PER_OWNERREAD as NV_PERM_OWNERREAD,
  TPM_NV_PER_OWNERWRITE as NV_PERM_OWNERWRITE, TPM_NV_PER_PPREAD as NV_PERM_PPREAD,
  TPM_NV_PER_PPWRITE as NV_PERM_PPWRITE, TPM_NV_PER_READ_STCLEAR as NV_PERM_READ_STCLEAR,
  TPM_NV_PER_WRITE_STCLEAR as NV_PERM_WRITE_STCLEAR, TPM_NV_PER_WRITEDEFINE as NV_PERM_WRITEDEFINE,
};
#[cfg(all(feature = "tpm2_0", not(feature = "tpm1_2")))]
pub use crate::tlcl::tpm20::constants::{
  TPMA_NV_AUTHREAD as NV_PERM_AUTHREAD, TPMA_NV_AUTHWRITE as NV_PERM_AUTHWRITE,
  TPMA_NV_OWNERREAD as NV_PERM_OWNERREAD, TPMA_NV_OWNERWRITE as NV_PERM_OWNERWRITE,
  TPMA_NV_PLATFORMCREATE as NV_PERM_PLATFORMCREATE, TPMA_NV_PPREAD as NV_PERM_PPREAD,
  TPMA_NV_PPWRITE as NV_PERM_PPWRITE, TPMA_NV_READ_STCLEAR as NV_PERM_READ_STCLEAR,
  TPMA_NV_WRITE_STCLEAR as NV_PERM_WRITE_STCLEAR, TPMA_NV_WRITEDEFINE as NV_PERM_WRITEDEFINE,
};
#[cfg(all(feature = "tpm1_2", feature = "tpm2_0"))]
pub use crate::tlcl::tpm20::constants::{
  TPMA_NV_AUTHREAD as NV_PERM_AUTHREAD, TPMA_NV_AUTHWRITE as NV_PERM_AUTHWRITE,
  TPMA_NV_OWNERREAD as NV_PERM_OWNERREAD, TPMA_NV_OWNERWRITE as NV_PERM_OWNERWRITE,
  TPMA_NV_PPREAD as NV_PERM_PPREAD, TPMA_NV_PPWRITE as NV_PERM_PPWRITE,
  TPMA_NV_READ_STCLEAR as NV_PERM_READ_STCLEAR, TPMA_NV_WRITE_STCLEAR as NV_PERM_WRITE_STCLEAR,
  TPMA_NV_WRITEDEFINE as NV_PERM_WRITEDEFINE,
};

#[cfg(feature = "tpm1_2")]
pub mod tpm12 {
  pub use crate::tlcl::tpm12::constants::{
    TPM_NV_PER_AUTHREAD as NV_PERM_AUTHREAD, TPM_NV_PER_AUTHWRITE as NV_PERM_AUTHWRITE,
    TPM_NV_PER_GLOBALLOCK as NV_PERM_GLOBALLOCK, TPM_NV_PER_OWNERREAD as NV_PERM_OWNERREAD,
    TPM_NV_PER_OWNERWRITE as NV_PERM_OWNERWRITE, TPM_NV_PER_PPREAD as NV_PERM_PPREAD,
    TPM_NV_PER_PPWRITE as NV_PERM_PPWRITE, TPM_NV_PER_READ_STCLEAR as NV_PERM_READ_STCLEAR,
    TPM_NV_PER_WRITE_STCLEAR as NV_PERM_WRITE_STCLEAR,
    TPM_NV_PER_WRITEDEFINE as NV_PERM_WRITEDEFINE,
  };
}

#[cfg(feature = "tpm2_0")]
pub mod tpm20 {
  pub use crate::tlcl::tpm20::constants::{
    TPMA_NV_AUTHREAD as NV_PERM_AUTHREAD, TPMA_NV_AUTHWRITE as NV_PERM_AUTHWRITE,
    TPMA_NV_OWNERREAD as NV_PERM_OWNERREAD, TPMA_NV_OWNERWRITE as NV_PERM_OWNERWRITE,
    TPMA_NV_PLATFORMCREATE as NV_PERM_PLATFORMCREATE, TPMA_NV_PPREAD as NV_PERM_PPREAD,
    TPMA_NV_PPWRITE as NV_PERM_PPWRITE, TPMA_NV_READ_STCLEAR as NV_PERM_READ_STCLEAR,
    TPMA_NV_WRITE_STCLEAR as NV_PERM_WRITE_STCLEAR, TPMA_NV_WRITEDEFINE as NV_PERM_WRITEDEFINE,
  };
}
