d= /run/vpd 0755 root root

# Recursively clean up old directories. All "state" is in /run/vpd these days.
# These files were obsolete and are being cleaned out as of R-127.
R /mnt/stateful_partition/unencrypted/cache/vpd
R /var/cache/echo
R /var/cache/vpd

# Remove old symlink.
# This file was obsolete and is being cleaned out as of R-127.
r /var/log/vpd_2.0.txt
